import type { MetadataRoute } from "next";

// Makes the web app installable as a desktop app on macOS, Windows and Linux
// (Chrome/Edge "Install", Safari "Add to Dock"), and as a home-screen app on
// mobile. Same rationale as the Android shell in `mobile/`: ship the polished
// responsive interface we already have rather than rebuild it per platform.
// Icons are generated by `node scripts/make-icons.mjs`.
// See: node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/01-metadata/manifest.md
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "Internal — Docs & Tasks",
    short_name: "Internal",
    description: "A combined Notion + Linear workspace.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    categories: ["productivity", "business"],
    // Opening an app link focuses the window that is already running instead of
    // stacking up duplicates — every route here is a live workspace view.
    launch_handler: { client_mode: "focus-existing" },
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
